### ISSUE TITLE
What's the performance of this method, how much time and computing resources does it require per inference?

### ISSUE THREAD

**Issue by heipi33** [cvg/EMAP#1]
Could you please provide details on the performance overhead, required computational resources, and the average time consumption for running the experiments described in your paper? Specifically, I am interested in:

The hardware configuration used (e.g., CPU, GPU, RAM).
The average runtime for each experiment.
Any significant performance bottlenecks encountered.
Thank you.

**Comment by rayeeli** [comment]
Thank you for your interest in our work. We used a vanilla NeRF MLP model, which needs longer training times compared to current advanced NeRF models but requires minimal hardware. The minimal GPU requirement is 1080ti. Our experiments were conducted using 2080ti. For the average runtime, ABC-NEF_Edge Dataset: ~3 hours per object, Replica and DTU Datasets: ~12 hours per scene.
