### ISSUE TITLE
Invalid .zip files for the datasets

### ISSUE THREAD

**Issue by C-H-Chien** [cvg/EMAP#2]
When trying to download the datasets provided by the [huggingface](https://huggingface.co/datasets/rayeeli/EMAP), the .zip files are invalid, _i.e._, when using `python scripts/download_data.py`, an error message pops up saying `zipfile.BadZipFile: File is not a zip file`.

**Comment by rayeeli** [comment]
Thanks for your question. You can first download these zip files from https://huggingface.co/datasets/rayeeli/EMAP and then unzip them under EMAP/data. We are currently investigating the issue with the broken zip files.

**Comment by C-H-Chien** [comment]
Hi! Thanks for the reply. I tried again but the same issue remains; it throws the following message:
```
Archive:  DTU_Edge.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of DTU_Edge.zip or
        DTU_Edge.zip.zip, and cannot find DTU_Edge.zip.ZIP, period.
```
Thanks for the investigation and looking forward to the update.

**Comment by rayeeli** [comment]
We have updated the dataset download code. You should be able to download them by running “python scripts/download_data.py ”.

**Comment by C-H-Chien** [comment]
It works. Thanks!
