### ISSUE TITLE
Questions about Edge Direction Calculation

### ISSUE THREAD

**Issue by zhenshan0127** [cvg/EMAP#6]
Hello,

Thanks for this amazing work! I have a question about section of Edge Direction in the paper. I think there are two possible directions along the edge, so how to determine the desired one?

Then, I find the function [def line_fitting(endpoints)](https://github.com/cvg/EMAP/blob/d6c84236045a09757a7797f4a98f355c02716de4/src/edge_extraction/edge_fitting/line_fit.py#L183C1-L183C28). Based on my understanding, two points are finally used to represent the edge, so there is no need to determine its direction.  Is my understanding correct?

Thanks for your time and patience.

Regards,
Zhenshan

**Comment by rayeeli** [comment]
Hi Zhenshan, 

Thanks for your question. Yes, you are right. Our final edge representation is endpoints for lines and Bezier curves for curves, and they are all non-directional. Edge directions are used to connect the originally extracted point clouds from UDF fields into polylines.

Our extracted edge directions on the same edge might have opposite directions. Thus, we connect points in both forward and backward directions to form polylines and avoid selecting desired directions (see [forward](https://github.com/cvg/EMAP/blob/main/src/edge_extraction/edge_fitting/main.py#L108) and [backward](https://github.com/cvg/EMAP/blob/main/src/edge_extraction/edge_fitting/main.py#L165) connections).

Best,

**Comment by Lzshanshan** [comment]
Hello @rayeeli,

Thanks for your quick and detailed explanation.

Regards,
Zhenshan

**Comment by zhenshan0127** [comment]
Hello @rayeeli,

Thanks for your quick and detailed explanation.

Regards,
Zhenshan
